CREATE TABLE `Chats` (
  `id` int NOT NULL AUTO_INCREMENT,
  `status` varchar(255) NOT NULL DEFAULT 'pending',
  `lastMessage` text,
  `contactId` int DEFAULT NULL,
  `userId` int DEFAULT NULL,
  `createdAt` datetime(6) NOT NULL,
  `updatedAt` datetime(6) NOT NULL,
  `isGroup` tinyint(1) NOT NULL DEFAULT '0',
  `unreadMessages` int DEFAULT NULL,
  `queueId` int DEFAULT NULL,
  `avaluationGrade` int DEFAULT NULL,
  `chatbot` tinyint(1) DEFAULT '0',
  `queueOptionId` int DEFAULT NULL,
  `categoryId` int DEFAULT NULL,
  `subject` varchar(255) NOT NULL,
  `priority` varchar(255) NOT NULL,
  `phoneId` int DEFAULT NULL,
  `origin` varchar(255) NOT NULL DEFAULT 'whatsapp',
  `deletedAt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `contactId` (`contactId`) USING BTREE,
  KEY `userId` (`userId`) USING BTREE,
  KEY `Chats_queueId_foreign_idx` (`queueId`) USING BTREE,
  KEY `Chats_queueOptionId_foreign_idx` (`queueOptionId`),
  KEY `Chats_categoryId_foreign_idx` (`categoryId`),
  KEY `Chats_phoneId_foreign_idx` (`phoneId`),
  CONSTRAINT `Chats_categoryId_foreign_idx` FOREIGN KEY (`categoryId`) REFERENCES `Categories` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Chats_ibfk_1` FOREIGN KEY (`contactId`) REFERENCES `Contacts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Chats_ibfk_2` FOREIGN KEY (`userId`) REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Chats_phoneId_foreign_idx` FOREIGN KEY (`phoneId`) REFERENCES `Phones` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Chats_queueId_foreign_idx` FOREIGN KEY (`queueId`) REFERENCES `Queues` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `Chats_queueOptionId_foreign_idx` FOREIGN KEY (`queueOptionId`) REFERENCES `QueueOptions` (`id`) ON DELETE SET NULL ON UPDATE SET NULL
);


CREATE TABLE `TicketMessages` (
  `id` varchar(255) NOT NULL,
  `body` text NOT NULL,
  `ack` int NOT NULL DEFAULT '0',
  `read` tinyint(1) NOT NULL DEFAULT '0',
  `mediaType` varchar(255) DEFAULT NULL,
  `mediaUrl` varchar(255) DEFAULT NULL,
  `ticketId` int NOT NULL,
  `createdAt` datetime(6) NOT NULL,
  `updatedAt` datetime(6) NOT NULL,
  `fromMe` tinyint(1) NOT NULL DEFAULT '0',
  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',
  `contactId` int DEFAULT NULL,
  `quotedMsgId` varchar(255) DEFAULT NULL,
  `isPrivate` tinyint(1) NOT NULL DEFAULT '0',
  `userId` int DEFAULT NULL,
  `chatHistoryId` int DEFAULT NULL,
  `chatbotFlowId` text,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `ticketId` (`ticketId`) USING BTREE,
  KEY `TicketMessages_contactId_foreign_idx` (`contactId`) USING BTREE,
  KEY `TicketMessages_quotedMsgId_foreign_idx` (`quotedMsgId`) USING BTREE,
  KEY `TicketMessages_userId_foreign_idx` (`userId`),
  KEY `TicketMessages_chatHistoryId_foreign_idx` (`chatHistoryId`),
  CONSTRAINT `TicketMessages_chatHistoryId_foreign_idx` FOREIGN KEY (`chatHistoryId`) REFERENCES `ChatHistories` (`id`),
  CONSTRAINT `TicketMessages_contactId_foreign_idx` FOREIGN KEY (`contactId`) REFERENCES `Contacts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `TicketMessages_ibfk_2` FOREIGN KEY (`ticketId`) REFERENCES `Tickets` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `TicketMessages_quotedMsgId_foreign_idx` FOREIGN KEY (`quotedMsgId`) REFERENCES `TicketMessages` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `TicketMessages_userId_foreign_idx` FOREIGN KEY (`userId`) REFERENCES `Users` (`id`)
) 